### ISSUE TITLE
Pods won't start due to read-only volumes

### ISSUE THREAD

**Issue by DevOpsCow** [StackStorm/st2-docker#100]
Starting st2 in minikube following the directions on https://github.com/StackStorm/st2-docker/tree/master/runtime/kubernetes-1ppc

minikube version: v0.25.0
kubectl version: Client Version: 1.9.2, Server Version: v1.9.0
Docker version 17.05.0-ce, build 89658be
on Ubuntu 14.04

However the Jobs won't execute successfully:
```
kubectl get jobs
NAME                        DESIRED   SUCCESSFUL   AGE
init-st2-default-files      1         0            19m
init-st2-register-content   1         0            19m
```

I found errors related to a read-only mount and missing folders: 
```
# logs for init-st2-default-files
mount: block device /opt/stackstorm is write-protected, mounting read-only
mount: cannot mount block device /opt/stackstorm read-only

# logs for st2-register-content
[...]
ValueError: Directory "/opt/stackstorm/packs/chatops" doesn't exist
```

Any idea what might be going on, and what I need to do to fix it?

Thanks!

**Comment by shusugmt** [comment]
I suspect volumes are not claimed properly. Can you show the output of `kubectl get pvc` and `kubectl get pv` ?

It should look like this:

```
$ kubectl get pvc
NAME              STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
st2-packs         Bound     pvc-7b78b1cc-060d-11e8-b401-023b0fefc461   100Mi      RWX            standard       6m
st2-virtualenvs   Bound     pvc-7b7f02d0-060d-11e8-b401-023b0fefc461   100Mi      RWX            standard       6m
```

```
$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                     STORAGECLASS   REASON    AGE
pvc-7b78b1cc-060d-11e8-b401-023b0fefc461   100Mi      RWX            Delete           Bound     default/st2-packs         standard                 6m
pvc-7b7f02d0-060d-11e8-b401-023b0fefc461   100Mi      RWX            Delete           Bound     default/st2-virtualenvs   standard                 6m
```

**Comment by udaymadu** [comment]
I am also facing same issue, i ahve vsphere-rwo and only one node cluster and init containers are not coming up.
$ kubectl logs init-st2-register-content-fr577
Adding password for user admin
/st2-docker/bin/entrypoint.sh: ignoring /st2-docker/entrypoint.d/*

+ PACKS='chatops core default linux packs'
+ for PACK in '${PACKS}'
+ st2-register-content --config-file /etc/st2/st2.conf --register-all --register-setup-virtualenvs --register-pack /opt/stackstorm/packs/chatops
2018-08-23 19:04:28,304 INFO [-] Connecting to database "st2" @ "mongo:27017" as user "None".
2018-08-23 19:04:28,623 INFO [-] =========================================================
2018-08-23 19:04:28,623 INFO [-] ############## Registering triggers #####################
2018-08-23 19:04:28,623 INFO [-] =========================================================
2018-08-23 19:04:28,623 WARNING [-] Failed to register sensors: Directory "/opt/stackstorm/packs/chatops" doesn't exist
Traceback (most recent call last):
  File "/usr/bin/st2-register-content", line 22, in <module>
    sys.exit(content_loader.main(sys.argv[1:]))
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 389, in main
    register_content()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 336, in register_content
    register_triggers()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 146, in register_triggers
    raise e
ValueError: Directory "/opt/stackstorm/packs/chatops" doesn't exist

have you resolved it..

**Comment by matejkramny** [comment]
try changing `init-st2.yml` to:

```
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: stackstorm
  name: init-st2-default-files
spec:
  template:
    metadata:
      name: init-st2-default-files
    spec:
      containers:
      - name: init-st2-default-files
        image: stackstorm/stackstorm:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
        command:
        - bash
        - "-c"
        - >-
          rsync -avi /opt/stackstorm/packs-mounted/ /opt/stackstorm/packs/
        envFrom:
        - configMapRef: { name: st2 }
        - configMapRef: { name: st2-rabbitmq }
        - configMapRef: { name: st2-postgres }
        volumeMounts:
        - name: st2-packs
          mountPath: /opt/stackstorm/packs-mounted
        - name: st2-virtualenvs
          mountPath: /opt/stackstorm/virtualenvs
      volumes:
      - name: st2-packs
        persistentVolumeClaim:
          claimName: st2-packs
      - name: st2-virtualenvs
        persistentVolumeClaim:
          claimName: st2-virtualenvs
      restartPolicy: Never
```

i don't understand why mounting a volume inside the container is a good idea. See the different job command to rsync the default packs.

Hope this helps you.
