### ISSUE TITLE
Add Integration Tests

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-docker#197]
There is a CI check which mimicks quick smoke tests for the Docker deployment to verify it somewhat works:
https://github.com/StackStorm/st2-docker/blob/02c7d2f0a046dbc3cb2b6aac788ce065c1fd6bde/.circleci/config.yml#L33-L38

Better way would be following the solution in existing stackstorm-ha repo and adopt proper `BATS` integration tests:
https://github.com/StackStorm/stackstorm-ha/blob/master/tests/st2tests.sh that would check system aliveness.

Implement these tests so the proper `docker-compose` entry point to run would be as simple as: 
`docker-compose run tests`

**Comment by minsis** [comment]
Is this something to run inside of a container?

**Comment by armab** [comment]
Right, something like `tests` container with the st2 CLI and BATS framework installed to run the `st2` checks in an automated way.

**Comment by blag** [comment]
We already run end-to-end tests with BATS for StackStorm/st2:

* https://github.com/StackStorm/st2tests/tree/master/test_helpers
* https://github.com/StackStorm/st2tests/tree/master/chatops
* https://github.com/StackStorm/st2tests/tree/master/cli
* https://github.com/StackStorm/st2tests/tree/master/docs

It might be useful to figure out which of those tests also cleanly work against an st2-docker instance and reuse those tests in integrations tests for this repo.

If we have that working, I would add that config to the StackStorm/st2 CI, so changes made there don't break st2-docker.

**Comment by armab** [comment]
In this context it would be nice adding a couple of quick infra smoke tests verifying the st2 components/APIs are running, content was loaded and the system works OK in the Docker environment (https://github.com/StackStorm/stackstorm-ha/blob/master/tests/st2tests.sh).

**Comment by minsis** [comment]
Just kinda poking around at ideas here and maybe get some feedback.

Doing some research there's no real clean way of adding something like `st2tests` or `test` to the docker-compose file without it starting up with the rest of the stack. Doing some testing I created a 2nd docker-compose file called st2test.yaml which you can call with `docker-compose -f st2test.yaml up`. 

Its an extra flag to add to docker-compose, but I'm not seeing any other way to do something as simple as `docker-compose run test`

```yaml
version: '3'

services:
  st2test:
    image: ${ST2_IMAGE_REPO:-stackstorm/}st2actionrunner:${ST2_VERSION:-latest}
    environment:
      ST2_AUTH_URL: ${ST2_AUTH_URL:-http://st2auth:9100/}
      ST2_API_URL: ${ST2_API_URL:-http://st2api:9101/}
      ST2_STREAM_URL: ${ST2_STREAM_URL:-http://st2stream:9102/}
      ST2WEB_HTTPS: ${ST2WEB_HTTPS:-0}
    command: /st2test.sh
    volumes:
      - ./scripts/st2test.sh:/st2test.sh:ro
    networks:
      - st2-docker_private

networks:
  st2-docker_private:
    external: true
```

Thoughts?

P.S. If y'all aren't planning to add some kind of specialized test container to st2-dockerfile that includes BATS, then a dockerfile will need to be created and docker-compose will need to run the dockerfile instead of pulling an image from your repo.
