### ISSUE TITLE
mistral doesn't work in Swarm mode

### ISSUE THREAD

**Issue by sanzaki** [StackStorm/st2-docker#83]
Hi,

I try to use Stackstorm 2.5.0 but it doesn't work well.

What I could do is...
1. Copy docker-compose file from github. 
2. Set proxy setting file in /etc/default 
3. execute $ st2ctl restart-component st2api / $ st2ctl restart-component st2actionrunner
I tried to execute "$ pack install acos" for test. It works well.  :)
4. Create action and workflow file.
5. I execute "$ st2 run test.mistral-basic cmd=date" and  get error... :(

Please tell me what I should do...

* /opt/stackstorm/packs/test/actions/mistral-basic.yaml
```
---
description: Run a local linux command
enabled: true
entry_point: workflows/mistral-basic.yaml
name: mistral-basic
pack: test
parameters:
  cmd:
    required: true
    type: string
runner_type: mistral-v2
```
* /opt/stackstorm/packs/test/actions/workflows/mistral-basic.yaml
```
version: '2.0'

test.mistral-basic:
    description: A basic workflow that runs an arbitrary linux command.
    type: direct
    input:
        - cmd
    output:
        stdout: <% $.stdout %>
    tasks:
        task1:
            action: core.local cmd=<% $.cmd %>
            publish:
                stdout: <% task(task1).result.stdout %>
                stderr: <% task(task1).result.stderr %>
```

* Result
```
| result          | {                                                            |
|                 |     "traceback": "  File                                     |
|                 | "/opt/stackstorm/st2/local/lib/python2.7/site-               |
|                 | packages/st2actions/container/base.py", line 119, in _do_run |
|                 |     (status, result, context) = runner.run(action_params)    |
|                 |   File "/opt/stackstorm/st2/local/lib/python2.7/site-        |
|                 | packages/retrying.py", line 49, in wrapped_f                 |
|                 |     return Retrying(*dargs, **dkw).call(f, *args, **kw)      |
|                 |   File "/opt/stackstorm/st2/local/lib/python2.7/site-        |
|                 | packages/retrying.py", line 206, in call                     |
|                 |     return attempt.get(self._wrap_exception)                 |
|                 |   File "/opt/stackstorm/st2/local/lib/python2.7/site-        |
|                 | packages/retrying.py", line 247, in get                      |
|                 |     six.reraise(self.value[0], self.value[1], self.value[2]) |
|                 |   File "/opt/stackstorm/st2/local/lib/python2.7/site-        |
|                 | packages/retrying.py", line 200, in call                     |
|                 |     attempt = Attempt(fn(*args, **kwargs), attempt_number,   |
|                 | False)                                                       |
|                 |   File "/opt/stackstorm/runners/mistral_v2/mistral_v2.py",   |
|                 | line 235, in run                                             |
|                 |     result =                                                 |
|                 | self.start_workflow(action_parameters=action_parameters)     |
|                 |   File "/opt/stackstorm/runners/mistral_v2/mistral_v2.py",   |
|                 | line 277, in start_workflow                                  |
|                 |     **options)                                               |
|                 |   File "/opt/stackstorm/st2/local/lib/python2.7/site-        |
|                 | packages/mistralclient/api/v2/executions.py", line 59, in    |
|                 | create                                                       |
|                 |     return self._create('/executions', data)                 |
|                 |   File "/opt/stackstorm/st2/local/lib/python2.7/site-        |
|                 | packages/mistralclient/api/base.py", line 100, in _create    |
|                 |     self._raise_api_exception(resp)                          |
|                 |   File "/opt/stackstorm/st2/local/lib/python2.7/site-        |
|                 | packages/mistralclient/api/base.py", line 160, in            |
|                 | _raise_api_exception                                         |
|                 |     error_message=error_data)                                |
|                 | ",                                                           |
|                 |     "error": "1"                                             |
|                 | }
| liveaction      | {                                                            |
|                 |     "runner_info": {                                         |
|                 |         "hostname": "7ac05376bbec",                          |
|                 |         "pid": 438                                           |
|                 |     },                                                       |
|                 |     "parameters": {                                          |
|                 |         "cmd": "date"                                        |
|                 |     },                                                       |
|                 |     "action_is_workflow": true,                              |
|                 |     "callback": {},                                          |
|                 |     "action": "test.mistral-basic",                          |
|                 |     "id": "5a1b5b2ee4dd3f01d06128e9"                         |
|                 | }
```

I have confirmed that simple actions described by python works well.
Only mistral actions doesn't work.
